### PR TITLE
SVG import/export! ARC fiting!, Manual 2D digitizing, Plugin help, Code cleanup, Helicut now obeys cutfeedz, Mesh slicing in negative Z height and 3D fliping, 3D mesh slicing, Removed some dependecies, Path closing plugin, Thread milling, Tabs improved! Cut fix. Spring pass! Better zstep UI, Autoleveling prescan, Probing improvements, Drag knife support, MAJOR CUTTING FIXES, Export .XYZ pointcloud file, Show active inputs in UI, Mesh slicing fixes

### PR DESCRIPTION
**Pull request by Harvie**
Add help box for plugins, see #806 #917

image

Also added help for individual plugin options activated by doubleclick:

image

SVG export:

image

zamek_koupelna

Added basic mesh manipulation to slicer plugin:

image

Added 3D slicing (useful for future 3D cam work):

image

image

I've added basic 2D digitizing feature to Probe page #929
image
Just jog and click to record the point!

I've added selectable exit strategies in cut operation. Primary function of this feature is to avoid crashing after threadmilling operation using helical cut:
image

UI to disable zstep:
image

Now we can scan margins of autoleveling area to see what's gonna be probed:

image

I've written first experimental dragknife plugin. #975

image

image

Arc fiting plugin! #921

image

Ramps now work for pockets:

image

BONUS photo:

image

I've been thoroughly documenting my though processes on bCNC in this graph :-D

### CODE REVIEW

**Comment by Harvie** [comment]
I would like to add mouseover tooltips to plugin options, but i can't figured out how to do it...

**Comment by Harvie** [comment]
@MARIOBASZ See #806 for details

**Comment by Harvie** [comment]
@vlachoudis Another juicy PR for you. Can you please pull? :-)

**Comment by Harvie** [comment]
@vlachoudis merge pls :o)

**Comment by Harvie** [comment]
@vlachoudis we are heading to conflicts with other developers again. can you please help?

**Comment by walterwissmann** [comment]
@Harvie :
Can you this Line make adjustable?
adjust

**Comment by Harvie** [comment]
@walterwissmann i would really **LOVE** to have this. But didn't figured out how to do it! Can you please send me a patch?

**Comment by walterwissmann** [comment]
Puh, i am not a code beast, sorry... but i will search ;-)

Other one:
I make a little Cutout 9,5mm deep in 3mm step. The last 0.5mm is missing:
pass9_5_fehlt
[Klotz_klein.txt](https://github.com/vlachoudis/bCNC/files/2430643/Klotz_klein.txt)


Also:
It makes sence to deactivate the 'tab,island' line after cut function. When anyone deactivates it not manually, the maschine can crash in the material:
deaktiviert

**Comment by Harvie** [comment]
Yes. i guess that tab blocks should be disabled by default.

**Comment by walterwissmann** [comment]
Have you seen the: The last 0.5mm is missing?

**Comment by Harvie** [comment]
@walterwissmann yes. should be gone now. i've introduced the problem while i was fixing that last layer was cut twice lol :-D

**Comment by walterwissmann** [comment]
@Harvie : 
An other little beauty mistake:
i have had cutout a pice in 9,5mm depth different heights of the tabs (-5, -8, -9.1)
After the '9.0 pass' comes a 'exiting'. The Spindel goes up and down... :-(
test_9_5

I know a little mistake. but time is money lol 
And: A little bit of fun is always good  ;-)

**Comment by Harvie** [comment]
@walterwissmann i am glad that you've spotted the problem. stuff like this always annoys me when i run big job. i'll try to figure it out...

**Comment by Harvie** [comment]
@walterwissmann try now.

**Comment by walterwissmann** [comment]
Another thx :-)
Will test it now...
btw in ~1980 to 1995 i also was a code beast as you now... But i give it up :-( 
now i can help you a little bit to make your code closer ;-)

**Comment by Harvie** [comment]
@walterwissmann i am no code beast in any means. i don't know how i happend to work on bCNC... i was going to mill some stuff and last thing i know is spending nights on developing bCNC not milling anything lol.

Anyway. I have small TODO list of features that i want in bCNC and it's nearly finished. Then i will hopefully leave the development to other guys :-) But of course, even then i'll try to fix all bugs that will evetualy arise from my code. For now i want to finish islands in pockets and fix bugs in overcuts. hopefully @vlachoudis will show up soon. My long term goal is new GUI with OpenGL and 3D CAM features. But i don't have time to work on this right now, but at least i've prepared some stuff if somebody else will be able to continue.

**Comment by walterwissmann** [comment]
too bad Harvie to heare this...

My wish for you would be that you briefly look at the calibration of the probe camera in its position.
kamera

I have the probe camera mounted on a +X and -Y Position from the Spindle.
p1120738

On this side on the wiki (see **calibration**):
https://github.com/vlachoudis/bCNC/wiki/Probe-Camera-Alignment
the probe camera was mountet in a -X and +Y Position from the Spindle:
camera_05


So my wish to you:
Can you take a quick look at the probe camera code to get the correct signs during calibration?

**Comment by MARIOBASZ** [comment]
A lot of work and great contributions, I thank you! The islands in your pocket would be very good. Look at the problems I took a few steps to optimize the design for pcb with your contributions.

**Comment by walterwissmann** [comment]
Also to you Mario, many thanks!
It wouldn't be nice when your code and Harvey's code come together in one release :-)

**Pull request merged**
