### PR TITLE
Increase radius of arcs in templates to avoid error:34 when executing gcode

### LINKED ISSUE #1355: Jigsaw plugin generates too small radius.
Arcs generated by jigsaw plugin have too small radius - grbl fails with error:33 or error:34. [Workaround](https://github.com/kestassf/bCNC/commit/423bac4db95a2120753f32cfb3d8bd49f8b80a84#diff-420688194d2fe56134c7ec64ab6c8766) helped, but I'm not sure if it is correct/complete fix.

~/.bCNC:

    [Jigsaw]
    name = 
    width = 140.0
    height = 130.0
    piece_count = 40
    random_seed = 1
    threshold = 1.2
    tap_shape = basic

Failing line:

    g3 x8.5318 y16.4551 r3.4256
    ok
    g3 x15.0981 y16.9545 r3.1934
    error:34

### PR DESCRIPTION
**Pull request by gcobos**
Fixes #1355

### CODE REVIEW

**Review by rschell — COMMENTED** [review]
I can confirm that changes are necessary, but these may not be sufficient.  This commit allows the job to run on my grblhal machine (100x80, 300 count, basic jigsaw) to about 80 percent down the x axis pass, then stops with error 34.  Here are a few lines preceding the error:

g3x75y16r3.6452
ok
g3x74.9714y17.5585r3.5761
ok
g2x75.4381y18.3566r1.2363
ok
g3x75.9958y18.0391r0.9844
ok
g3x76.1287y19.2722r0.8125
ok
g3x75.4175y18.986r0.946
ok
g2x74.8676y19.7975r1.1842
ok
g3x75y21.3333r3.6452
ok
g3x74.9863y22.9521r3.605
ok
g2x75.4863y23.4268r1.2279
ok
g3x75.9751y23.1196r0.9554
ok
g3x76.038y24.9517r0.9091
error:34

**Review by rschell — COMMENTED** [review]
try bumping lines 96, 97 and 98 up by one to 32, 31, 32 respectively.

**Comment by gcobos** [comment]
I'll recheck this during the weekend. I need to rethink how the curves are scrambled / scaled, in case there's a way to control those issues with error: 34

**Review by rschell — COMMENTED** [review]
was having trouble tracking the change to "self.r" whether the divisor was 3.0 or 5.0.  Not sure the change #1355 made any difference.  Still seams to require the changes to the arc statements.

**Comment by rschell** [comment]
On a feature note, it would be nice if the algorithm would allow for the piece sizes to be randomized as well, i.e. some pieces smaller/larger than others.  Would require establishing a matrix of x, y coordinates for each intersection, with each intersection deviating a small percentage of the total average size.

**Comment by gcobos** [comment]
> was having trouble tracking the change to "self.r" whether the divisor was 3.0 or 5.0. Not sure the change #1355 made any difference. Still seams to require the changes to the arc statements.

When removing the negative offset, it's fine to allow the positive offset to be bigger (diving by 3, instead of 5). I have tried with this puzzle and I didn't encounter anymore the error: 34. Yes, I also included the changes to the arcs in the latest commit. Yesterday, I tried this puzzle and I couldn't see an error.
Width: 100
Height: 80
Pieces: 1000
Difference: 1.2
Shape: basic

**Comment by gcobos** [comment]
Is there anyone with permissions to merge pull requests here?

**Comment by Harvie** [comment]
Thanks

**Pull request merged**
