### PR TITLE
Box plugin does not work

### PR DESCRIPTION
**Pull request by SMU81**
with this change the box plugin works.

### CODE REVIEW

**Comment by Harvie** [comment]
Thanks! Have you tested both python2 and 3?

**Comment by SMU81** [comment]
no, sorry. I have only installed Python 3.8.1

**Comment by GitHubCaps** [comment]
@Harvie I tested on PY2 and it to still works. I have noticed a lot of people have been adding list to zip recently. I know that 2's zip builds and returns a list, whereas 3's zip returns a lazy iterator. PY2 returns an iterable. There are ways to achieve the same effect...

Anyways, after a quick grep, the other files that may be worth changing and testing are the following, for anyone up to the task.

```
/CNC.py:981:		pairs = zip("xyz",v)                                              # PY2
/CNC.py:981:		pairs = list(zip("xyz",v))                                        # PY3 #1363

/CNC.py:989:		return CNC.gcode(g, zip("xyz",v) + zip("ij",ijk[:2]))             # PY2
/CNC.py:989:		return CNC.gcode(g, list(zip("xyz",v)) + list(zip("ij",ijk[:2]))) # PY3 #1363

/Updates.py:133:		for a, b in zip(av, bv):
/lib/bmath.py:351:		for a,b in zip(self, v):
/lib/bmath.py:436:		for a,b in zip(self, v):
/lib/bmath.py:1412:	for x,y in zip(X,Y):
/lib/bmath.py:1919:	for i,n in zip(ints, nums):
/lib/bpath.py:1701:				xy = list(zip(dxf.convert(entity[10],units),
/lib/dxf.py:533:			xyz  = zip(self[10], self[20], self[30])
/lib/dxf.py:1382:#				xy = zip(entity[10], entity[20])
/lib/spline.py:244:#	for i,xyz in enumerate(zip(x,y,z)):
/lib/spline.py:475:				xy = zip(entity[10], entity[20])
/lib/spline.py:477:				#for a,b in zip(x,y):
/lib/tkExtra.py:1522:		if last: return zip(*result)
/lib/ttf.py:765:			self.pairs = zip(names, items)
/lib/svg/path/path.py:371:        for s, o in zip(self._segments, other._segments):
/plugins/box.py:198:		block.append(CNC.gcode(0, zip("XY",pos[:2])))
/plugins/flatten.py:56:		for x,y in zip(xR,yR):
/plugins/flatten.py:206:			for x,y in zip(xP,yP):
/plugins/flatten.py:213:			for x,y in zip(xB,yB):
/plugins/hilbert.py:56:		xi,yi = zip(*(self.hilbert(0.0,0.0,size,0.0,0.0,size,n)))
/plugins/hilbert.py:70:			for x,y in zip(xi,yi):
/plugins/pyrograph.py:171:			for x,y,f in zip(xH,yH,fH):
/plugins/pyrograph.py:180:			for x,y,f in zip(xV,yV,fV):
/plugins/spirograph.py:70:		xi,yi = zip(*(self.calc_dots()))
/plugins/spirograph.py:84:			for x,y in zip(xi,yi):
```

**Comment by GitHubCaps** [comment]
@Harvie I tested on PY2 and it to still works. I have noticed a lot of people have been adding list to zip recently. I know that 2's zip builds and returns a list, whereas 3's zip returns a lazy iterator. PY2 returns an iterable. There are ways to achieve the same effect...

Anyways, after a quick grep, the other files that may be worth changing and testing are the following, for anyone up to the task.

```
/CNC.py:981:		pairs = zip("xyz",v)                                              # PY2
/CNC.py:981:		pairs = list(zip("xyz",v))                                        # PY3 #1363

/CNC.py:989:		return CNC.gcode(g, zip("xyz",v) + zip("ij",ijk[:2]))             # PY2
/CNC.py:989:		return CNC.gcode(g, list(zip("xyz",v)) + list(zip("ij",ijk[:2]))) # PY3 #1363

/Updates.py:133:		for a, b in zip(av, bv):
/lib/bmath.py:351:		for a,b in zip(self, v):
/lib/bmath.py:436:		for a,b in zip(self, v):
/lib/bmath.py:1412:	for x,y in zip(X,Y):
/lib/bmath.py:1919:	for i,n in zip(ints, nums):
/lib/bpath.py:1701:				xy = list(zip(dxf.convert(entity[10],units),
/lib/dxf.py:533:			xyz  = zip(self[10], self[20], self[30])
/lib/dxf.py:1382:#				xy = zip(entity[10], entity[20])
/lib/spline.py:244:#	for i,xyz in enumerate(zip(x,y,z)):
/lib/spline.py:475:				xy = zip(entity[10], entity[20])
/lib/spline.py:477:				#for a,b in zip(x,y):
/lib/tkExtra.py:1522:		if last: return zip(*result)
/lib/ttf.py:765:			self.pairs = zip(names, items)
/lib/svg/path/path.py:371:        for s, o in zip(self._segments, other._segments):
/plugins/box.py:198:		block.append(CNC.gcode(0, zip("XY",pos[:2])))
/plugins/flatten.py:56:		for x,y in zip(xR,yR):
/plugins/flatten.py:206:			for x,y in zip(xP,yP):
/plugins/flatten.py:213:			for x,y in zip(xB,yB):
/plugins/hilbert.py:56:		xi,yi = zip(*(self.hilbert(0.0,0.0,size,0.0,0.0,size,n)))
/plugins/hilbert.py:70:			for x,y in zip(xi,yi):
/plugins/pyrograph.py:171:			for x,y,f in zip(xH,yH,fH):
/plugins/pyrograph.py:180:			for x,y,f in zip(xV,yV,fV):
/plugins/spirograph.py:70:		xi,yi = zip(*(self.calc_dots()))
/plugins/spirograph.py:84:			for x,y in zip(xi,yi):
```

**Comment by GitHubCaps** [comment]
@Harvie I tested on PY2 and it to still works. I have noticed a lot of people have been adding list to zip recently. I know that 2's zip builds and returns a list, whereas 3's zip returns a lazy iterator. PY2 returns an iterable. There are ways to achieve the same effect...

Anyways, after a quick grep, the other files that may be worth changing and testing are the following, for anyone up to the task.

```
/CNC.py:981:		pairs = zip("xyz",v)                                              # PY2
/CNC.py:981:		pairs = list(zip("xyz",v))                                        # PY3 #1363

/CNC.py:989:		return CNC.gcode(g, zip("xyz",v) + zip("ij",ijk[:2]))             # PY2
/CNC.py:989:		return CNC.gcode(g, list(zip("xyz",v)) + list(zip("ij",ijk[:2]))) # PY3 #1363

/Updates.py:133:		for a, b in zip(av, bv):
/lib/bmath.py:351:		for a,b in zip(self, v):
/lib/bmath.py:436:		for a,b in zip(self, v):
/lib/bmath.py:1412:	for x,y in zip(X,Y):
/lib/bmath.py:1919:	for i,n in zip(ints, nums):
/lib/bpath.py:1701:				xy = list(zip(dxf.convert(entity[10],units),
/lib/dxf.py:533:			xyz  = zip(self[10], self[20], self[30])
/lib/dxf.py:1382:#				xy = zip(entity[10], entity[20])
/lib/spline.py:244:#	for i,xyz in enumerate(zip(x,y,z)):
/lib/spline.py:475:				xy = zip(entity[10], entity[20])
/lib/spline.py:477:				#for a,b in zip(x,y):
/lib/tkExtra.py:1522:		if last: return zip(*result)
/lib/ttf.py:765:			self.pairs = zip(names, items)
/lib/svg/path/path.py:371:        for s, o in zip(self._segments, other._segments):
/plugins/box.py:198:		block.append(CNC.gcode(0, zip("XY",pos[:2])))
/plugins/flatten.py:56:		for x,y in zip(xR,yR):
/plugins/flatten.py:206:			for x,y in zip(xP,yP):
/plugins/flatten.py:213:			for x,y in zip(xB,yB):
/plugins/hilbert.py:56:		xi,yi = zip(*(self.hilbert(0.0,0.0,size,0.0,0.0,size,n)))
/plugins/hilbert.py:70:			for x,y in zip(xi,yi):
/plugins/pyrograph.py:171:			for x,y,f in zip(xH,yH,fH):
/plugins/pyrograph.py:180:			for x,y,f in zip(xV,yV,fV):
/plugins/spirograph.py:70:		xi,yi = zip(*(self.calc_dots()))
/plugins/spirograph.py:84:			for x,y in zip(xi,yi):
```

**Comment by Harvie** [comment]
@GitHubCaps so you think `list(zip())` is ok on both python2 and 3?

**Comment by GitHubCaps** [comment]
No, not at all. We should not be changing anything in python 2's native
code. If else clauses are better in the this case. Python naturally uses
list, so you are actually putting a list inside of another list in some
cases, which makes it inefficient for 2, while 3 needs list because it now
has objects that requires the use of list to retrieve the info back.

**Comment by GitHubCaps** [comment]
Right now the problem is going to be how to implement changes for getting python3 to work,  but we also don't want to cripple python2 in the process. Those changes don't seem harmful at first because one might test in both and get good results, however if you run timeit on it, you will see that in fact, you just slowed down python2.

**Comment by Harvie** [comment]
I am ok with bCNC on python 2 slowing down a bit. The code will run on both and people will probably be able to gradualy transition to python 3 if they need faster processing. That way there's no need to cleanup anything once python 2 will not be needed.

**Comment by GitHubCaps** [comment]
I don't have a problem with it on my side, I use my own code. What I do see
are bugs being introduced to the code that will break bCNC from working
properly in either version. I haven't made any commits to rectify what I am
saying, however I know by just seeing what is being implemented is not
correct and isn't solving the issues for everyone. I am under the
impression that the project is meant to stay compatible with both, if that
is not an issue, then there probably should be another branch for Python 3
as to not break Python 2. One of the reasons I say this  (for example) is
the difference in configparser alone. There are so many changes at so many
levels, that won't make it easy on anyone to sort out. I really like this
project and would like to help out in any way that I can, however I just
don't agree in adding insult to injury, if that makes sense to you. And
yes, I agree with you, there is no reason why others can not update to the
latest and greatest version to gain all the benefits that Python 3 has to
offer  (other than our headaches to make it so)

**Comment by SMU81** [comment]
Maybe it is a solution to insert `from builtins import zip`. For this the future package must be installed.
`pip2 install future`

**Comment by DodoLaSaumure** [comment]
Dear @GitHubCaps 
I did not catch that list(zip) slows python2 and I made some commits with list(zip()), but after performing some speed tests, you are absolutely right.
I am sorry about this, I did not want to introduce regressions, but just help users to solve their issues.
I appreciate very much this project, too, and would not like to downgrade the code.

Do you think this could be an acceptable code ?

```
list1 = [1,2,3,4]
list2 = [5,6,7,8,9]

zipped = zip(list1,list2)
if type(zipped) is not list :
    zipped = list(zipped)
    
print (type(zipped))

for a,b in zipped :
    print (a,b)
```
it provides the following output
```
:~/workspace/toto$ python3 toto.py 
<class 'list'>
1 5
2 6
3 7
4 8
:~/workspace/toto$ python2 toto.py 
<type 'list'>
(1, 5)
(2, 6)
(3, 7)
(4, 8)

```

**Comment by DodoLaSaumure** [comment]
PS : 
a speed test gives the following results
```
import time
t0 = time.time()
list1 = range(10000)
list2 = range(10000)
for _ in range (10000):
    zipped = zip(list1,list2)
    if type(zipped) is not list :
        zipped = list(zipped)
t1 = time.time()
print ("ran in %f s"%(t1-t0))
```
```
:~/workspace/toto$ python2 tata.py 
ran in 13.079820 s
:~/workspace/toto$ python3 tata.py 
ran in 16.411839 s
```

**Comment by GitHubCaps** [comment]
@SMU81 I actually do not believe in using `from future`, `from past` or any packages like that. I mentioned that there are other solutions (actually, they already exist in `bCNC`) that solves the problems. There are only 3 plugins (box, midi2cnc and pyrograph) that use `glinev` and only `box` uses `garcv`. One way to solve this is to recode the plugins mentioned. The other is to use an `if` statement. The `if` is simple enough, however, I believe removing `glinev` and `garcv` will cleanup the code and help keep others from using it in the future.

As you may have noticed, there is `gline` and `garc` that use an explicit `for` loop. I would prefer those over a version dependent method that uses `zip`. The issue with `glinev` is not that it is an `object` in Python 3 that requires `list`, it is because `if feed is not None` can't `append` to an `object`. You see, you don't always need to use `list` with `zip` (even in Python 3), but in this case you do, if you need to `append`, for example. Simply put, for our use case, it never needed to be an `object` to begin with, which is the way it works in Python 2, it is already a `list` ready to be `append`ed.

Long story short: In Python 3 it makes sense for it to be an `object` in memory for large datasets. For our purpose, it makes absolutely no sense to create an `object` just to turn around and extract it back out!

As an example, to get by without recoding the aforementioned plugins:
```python
	@staticmethod
	def glinev(g, v, feed=None):
#		pairs = zip("xyz",v)
		pairs = zip("xyz",v) if OLD else list(zip("xyz",v))
		if feed is not None:
			pairs.append(("f",feed))
		return CNC.gcode(g, pairs)
```
uses:
```python
	@staticmethod
	def gcode(g, pairs): # See issue #1313 
		s = "g%d"%(g)
		for c,v in pairs:
			s += " %c%g"%(c, round(v,CNC.digits))
		return s
```
the above (#1313) could also be removed, after recoding almost every plugin in `bCNC`

Preferred method already in `bCNC` to be used instead:
```python
	@staticmethod
	def gline(x=None, y=None, z=None, **args):
		return CNC._goto(1,x,y,z,**args)
```
uses:
```python
	@staticmethod
	def _gcode(g, **args):
		s = "g%d"%(g)
		for n,v in args.items():
			s += ' ' + CNC.fmt(n,v)
		return s
```

@DodoLaSaumure

> I did not want to introduce regressions, but just help users to solve their issues.
I appreciate very much this project, too, and would not like to downgrade the code.

Same here! I know that I will be keeping Python 2 on some machines, if for no other reason than I simply have too many scripts that I am never going to port (probably take a couple of decades!)

 As far as the code, that would work, but I believe you are over thinking it. An `if` (as I pointed out above) will more than suffice. If you do, I would add a function to `Utils.py` in order to keep the code compact as possible, as I mentioned here:
> https://github.com/vlachoudis/bCNC/pull/1405#issuecomment-629590849

**Comment by Harvie** [comment]
@SMU81 there is already following code used all across the bCNC:

```
from __future__ import absolute_import
from __future__ import print_function
```

Is that different library to the `pip install future` ? `__future__` seems to be builtin in late python2 versions already...

**Comment by GitHubCaps** [comment]
@Harvie @SMU81 `future` is a 3rd party software meant to help users futurize their own code to Python3 standards. It is not meant to be used in a project such as this one. It merely evaluates your own code and applies fixes that it deems necessary (even if not necessary) and those fixes can even break your code. `from __future__` is a standard import in Python2 and Python3 doesn't use it. A good example is using `python2 -3 -m bCNC` from commandline. `-3` uses `__future__` and will print in the terminal `DeprecationWarning`s and other info to help aid you in the process.

Example: `python2 -3 -m bCNC -d`
```sh
new-config Utils <cfgparse.ConfigParser instance at 0x7f78fa902a70>
/home/user/.local/lib/python2.7/site-packages/numpy/core/overrides.py:6: DeprecationWarning: CObject type is not supported in 3.x. Please use capsule objects instead.
  from numpy.core._multiarray_umath import (
/home/user/.local/lib/python2.7/site-packages/numpy/core/_internal.py:204: DeprecationWarning: Overriding __eq__ blocks inheritance of __hash__ in 3.x
  class dummy_ctype(object):
/home/user/.local/lib/python2.7/site-packages/numpy/lib/mixins.py:63: DeprecationWarning: Overriding __eq__ blocks inheritance of __hash__ in 3.x
  class NDArrayOperatorsMixin(object):
/home/user/Downloads/GIT/GitHubCaps/bCNC/lib/svg_elements.py:723: DeprecationWarning: Overriding __eq__ blocks inheritance of __hash__ in 3.x
  class Color(int):
/home/user/Downloads/GIT/GitHubCaps/bCNC/lib/svg_elements.py:1413: DeprecationWarning: Overriding __eq__ blocks inheritance of __hash__ in 3.x
  class Angle(float):
/usr/lib/python2.7/abc.py:87: DeprecationWarning: Overriding __eq__ blocks inheritance of __hash__ in 3.x
  cls = super(ABCMeta, mcls).__new__(mcls, name, bases, namespace)
/home/user/.local/lib/python2.7/site-packages/future/utils/__init__.py:142: DeprecationWarning: Overriding __eq__ blocks inheritance of __hash__ in 3.x
  return meta(name, bases, d)
/home/user/.local/lib/python2.7/site-packages/PIL/Image.py:524: DeprecationWarning: Overriding __eq__ blocks inheritance of __hash__ in 3.x
  class Image(object):
/usr/lib/python2.7/dist-packages/serial/tools/list_ports_common.py:29: DeprecationWarning: Overriding __eq__ blocks inheritance of __hash__ in 3.x
  class ListPortInfo(object):
================================================================================
WARNING: bCNC has been recently ported to support both python v2.x and v3.x
Most things seem to work reasonably well in both python versions.
Please report any issues to: https://github.com/vlachoudis/bCNC/issues
================================================================================
/home/user/Downloads/GIT/GitHubCaps/bCNC/plugins/jigsaw.py:21: DeprecationWarning: Overriding __eq__ blocks inheritance of __hash__ in 3.x
  class Arc(object):
/usr/lib/python2.7/dist-packages/scipy/sparse/base.py:61: DeprecationWarning: Overriding __eq__ blocks inheritance of __hash__ in 3.x
  class spmatrix(object):
/usr/lib/python2.7/dist-packages/scipy/sparse/compressed.py:21: DeprecationWarning: Overriding __eq__ blocks inheritance of __hash__ in 3.x
  class _cs_matrix(_data_matrix, _minmax_mixin, IndexMixin):
/usr/lib/python2.7/dist-packages/scipy/linalg/blas.py:155: DeprecationWarning: CObject type is not supported in 3.x. Please use capsule objects instead.
  from scipy.linalg import _fblas
/usr/lib/python2.7/dist-packages/scipy/linalg/lapack.py:362: DeprecationWarning: CObject type is not supported in 3.x. Please use capsule objects instead.
  from scipy.linalg import _flapack
self.canvas.winfo_id(): 73400410
Using old style comports()!
Using old style comports()!
Using old style comports()!
```

Note that not only does it show warnings in `Python2.7` main files, but also for the loaded modules for `bCNC`. Also, while the code is running, you'll see warnings when it comes across something that is known not work in Python >2. What a lot of people seem to not realize is that there is already builtin ways to evaluate code so that fixes can be implemented. I would never suggest using a 3rd party fixer, they usually break about as much as they fix! Better to understand the differences between versions and go from there.

`from __future__` was backported along time ago to help ease migration to Python3.

This print statement will not work without the use of `from __future__ import print_function` in Python2, because `print` was not a function before.
```python
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/user/Downloads/GIT/GitHubCaps/bCNC/bCNC.py", line 38, in <module>
    import Utils
  File "Utils.py", line 137
    [print("%s = %r"%(x,y)) for x,y in sorted(k.items())]
         ^
SyntaxError: invalid syntax
```

**Comment by Harvie** [comment]
Thank you. This will be fixed as part of PR #1405

**Comment by Harvie** [comment]
Reportedly fixed in this PR. Please test and close this issue if everything is OK:
https://github.com/vlachoudis/bCNC/pull/1405#issuecomment-751580531

**Pull request closed without merging**
