### PR TITLE
Add mime-type to pendant for jpg and gif

### PR DESCRIPTION
**Pull request by jdiderik**
I have a webcam setup that takes snapshots. I integrated it into the pendant html, but by default baseHTTP in Python returns the jpg with a text/html.
Corrected this based on file extension jpg (and added gif while I was at it, could possibly do more types like png etc.)

### CODE REVIEW

**Comment by Effer** [comment]
Hi @jdiderik would you like to describe your setup more in details? How it works the webcam stuff?
It would be nice to have it all integrated in bCNC.

**Comment by jdiderik** [comment]
Sure thing, will have to get back to you on that tomorrow, times up for today...

**Comment by jdiderik** [comment]
@Effer , I have [fswebcam](https://www.raspberrypi.org/documentation/usage/webcams/) installed for now, combined with an old usb webcam, that grabs an image of the webcam every minute through a cronjob and saves it to the pendant directory.
I added a seperate page 'webcam.html' to the pendant directory with some simple code to refresh the webcam.jpg every minute. I would be happy to add it to the repo if that's ok with @vlachoudis 
My idea was that since bCNC is running a simple webserver, I could just add that to Pi without to much work, simple and crude but effective. I can now check (be it with a potential minute delay) if my job is still running.

It may even be a proper plugin for bCNC with configuration etc... but I'm very rusty in Python (despite being a professional web developer, I never got to using Python)

I am experimenting with uv4l streaming server and webrtc for live images which seems to be operating quite well, but thats in early stages and I'm looking for performance improvements on that. I hope to finish that next week. Will keep you posted.

**Comment by Effer** [comment]
Simple and crude.
I Like it.  Waiting for updates!

Filippo

----- Messaggio originale -----
Da: "Jeroen Diderik" <notifications@github.com>
Inviato: ‎23/‎10/‎2015 11:24
A: "vlachoudis/bCNC" <bCNC@noreply.github.com>
Cc: "Filippo" <f.rivato@gmail.com>
Oggetto: Re: [bCNC] Add mime-type to pendant for jpg and gif (#136)

@Effer , I have fswebcam installed for now, combined with an old usb webcam, that grabs an image of the webcam every minute through a cronjob and saves it to the pendant directory.
I added a seperate page 'webcam.html' to the pendant directory with some simple code to refresh the webcam.jpg every minute. I would be happy to add it to the repo if that's ok with @vlachoudis 
My idea was that since bCNC is running a simple webserver, I could just add that to Pi without to much work, simple and crude but effective. I can now check (be it with a potential minute delay) if my job is still running.
It may even be a proper plugin for bCNC with configuration etc... but I'm very rusty in Python (despite being a professional web developer, I never got to using Python)
I am experimenting with uv4l streaming server and webrtc for live images which seems to be operating quite well, but thats in early stages and I'm looking for performance improvements on that. I hope to finish that next week. Will keep you posted.

**Comment by vlachoudis** [comment]
Thanks! I think your camera.html could be also useful.

**Pull request merged**
