### PR TITLE
Smoothie comm improved and manual drill plugin

### PR DESCRIPTION
**Pull request by apshu**
-New smoothie commands 'fire' and 'switch' recognized
-Imporved stability for communication
-New plugin: Manual drilling mark generator for weak laser

### CODE REVIEW

**Comment by Harvie** [comment]
BTW do you use smoothie? Right now we are in trouble, because we don't have anyone to test latest git version with smoothieware. I don't have smoothieboard and i never used it. Can you please do some cutting using git master bCNC and smoothieboard? There's gonna be new bCNC release soon and i want to make sure, that there are no major issues with smoothie support. Thanks.

**Comment by apshu** [comment]
Hi Harvie,

    Happy new year!

   I am working on a smoothie based machine, but the electronics is not yet connected to the mechanics. I cannot test real-life runs.

   The only significant Smoothie related issue I have found is clearing error state from bCNC.
   When smoothie enters error state, bCNC detects and displays it. Clicking the "clear error message" does nothing. Manually issuing M999 clears error state and the bCNC state reflects it correctly... I will try to find the cause of this bug.

Regards,
    Attila

(Will refactor drillmark plugin and request a pull.)

**Comment by Harvie** [comment]
> I cannot test real-life runs.

Not really needed. Just test if the communication between smoothieboard and bCNC goes well (bCNC sends g-code and smoothie reports right coordinates)

> Manually issuing M999 clears error state and the bCNC state reflects it correctly... 

I guess we can add this to SMOOTHIE.py file

> (Will refactor drillmark plugin and request a pull.)

BTW if you just push more commits to the same branch, it will automaticaly update the pull request. no need to close it and create new...

**Comment by Harvie** [comment]
Than you!

**Pull request merged**
