### PR TITLE
Add stepover for End Mill

### PR DESCRIPTION
**Pull request by Effer**
Is this enough to add StepOver parameter to End Mill?

### CODE REVIEW

**Comment by vlachoudis** [comment]
Almost. It needs also to propagate in the "def update(" the value to CNC. I will do it

**Comment by vlachoudis** [comment]
By mistake I've close it before merging it. I'll do manually :)

**Comment by Effer** [comment]
No problem, I'll use it for pocketing tool.

**Comment by vlachoudis** [comment]
Ok done

**Pull request closed without merging**
