### PR TITLE
Create trochoidal_3D.py

### PR DESCRIPTION
**Pull request by MARIOBASZ**
Another trochoidal option:
At the moment, only select one block at a time (help is accepted).
Follow the path of the selected block, being able to be a path with different heights (3d). If the path is on the surface (for example two joined blocks) the path is with G0.
Work with trochoid path for milling with adaptive trochoids in the corners. Go back the same way with G1 instead of repeating trochoids. Enter the helical material, adjusting the descent per turn according to the zfeed speed (I am not sure if I have correctly calculated the descent angle).
I have canceled z and speed for before contact and for hard crust,
(For me it is useful that the tool goes down at maximum speed until z before contact, that it goes at a very slow speed before the bit touches the material to minimize the tool's shock effect, and slower speed to enter the sector of hard crosta) because perhaps it lacks sense in general.
Option of joints between trochoids:
1-warpedarc: A bow of greater diameter
2-Splices: Generates segments to give shape to a clotoid spiral to avoid jerk/shake/lash. However, contrary to what I had sought, GRBL slows down this type of movement. It may be viable if the next version allows more acceleration and control of shakes like G2Core.
3/4-One or two sides rectified
5-Straight splice
6-Cut: The splice also makes cut when returning
Personally I use 1 or 6
Slope: On roads with ramp descent, the distance between trochoids could be decreased.

### CODE REVIEW

**Comment by Harvie** [comment]
Congratulations for getting your git master up to date with upstream and passing Travis tests!
I will merge this, but can you please add some documentation about what this does and how is it used?

Especially adding `self.help = ` text (no need to use images). Also optionaly you can put long description to `self.variables` if needed. Look at `plugins/slicemesh.py` for example. There is both `self.help = ` and `self.variables = `, so you can use that...

**Comment by Harvie** [comment]
Also note that CodeFactor automatic test complains that `execute()` method in your plugin is very complex. In future you might consider splitting it to multiple smaller methods. Because this way nobody except you can understand the code. It's just too big.

But i don't care about CodeFactor in this case, since this is your plugin and it does not directly affect maintainability of bCNC. But if you were to merge such method directly to bCNC codebase i would be considering it a problem...

So as i said... I can merge this if you add documentation. But be carefull not to get lost in the forrest of code :-)

**Comment by MARIOBASZ** [comment]
@Harvie, I did not understand why the Github ads. I'm glad that you can climb without problems. The operation is like this:
Follow the route to follow. On it performs the trochoidal picking (as I gabia shown above with examples).
Currently, first I must make the path with trochoidal_path, int, out (about: I would repeat the route), adaptive or not (generates an alarm that trochoidal3d recognizes it, I also told you)
It is desirable to be able to combine both plugins in one, maybe you or someone contribute that help (I guess it's simple)
Sure you can add the adaptive in corners to your trochoid.

**Comment by Harvie** [comment]
> @Harvie, I did not understand why the Github ads.

Because we've configured code checks in this repository, so all code that goes in is tested. This way i don't need to manualy check the code before merging. If bCNC is broken, it will give us alarm not to merge broken code.

There are two checks right now "Travis CI" and "CodeFactor".
All bCNC code needs to pass at least "Travis" test. But it's also good idea to read CodeFactor complaints to see if there are some serious problems...

It happens automaticaly, so you don't need to wait for me. If the "Travis" is red, you know that i will not merge. You can read Travis details to see what is the problem. (Right now there is no Travis problem with your code, so i can merge.)

**Comment by MARIOBASZ** [comment]
thanks for your extensive explanation!
I will try to see if I can implement what I asked for above, or raise it as a new issue, you are with many things!
Let me know if you can put your trochoid or trochoid path together to make it work hidden instead of having to perform the two operations one after the other (and understand how to do it)
Hug.

**Comment by sfinexer** [comment]
@MARIOBASZ 
Probably, CodeFactor swears because of a lot of lines, right now I'll try to fix it.

**Comment by Harvie** [comment]
> Probably, CodeFactor swears because of a lot of lines

~400 LOC in single method. I have to agree that it's not really readable and it would be better to split it to smaller blocks to made it easier to understand. But as long as it's in the separate plugin and does not polute main bCNC codebase, i don't have any problem with that.

> right now I'll try to fix it.

No need, but i need you to add the help for the plugin, because in the past i was not able to understand how to use it.

**Comment by MARIOBASZ** [comment]
@Harvie, I've managed to call trochoid_path from trochoidal, and I put it in extract all segments:
def extractAllSegments (self, app, selectedBlock):

# app.trochprofile_bcnc (trochcutdiam, direction, self ["offset"], self ["overcut"], self ["adaptive"], cornerradius, CNC.vars ["diameter"], name) # << diameter only to information
app.trochprofile_bcnc (6.0, "In", 0, 0, 1, 3.0, CNC.vars ["diameter"], "pp") # << diameter only to information
  However, it extracts the path of the selected block instead of the path created by trochoid_path.
If you can help me, I will upload the modifications together with the help, but, I will upload the aids so that I can merge it and later so that from here I generate the result without having to generate the trochoidal route before (it will be easier and avoid errors of selecting two times trochoidal cutting diameter (virtual tool) and possible error of the bit used (real tool for the generation of adaptive corners)

**Comment by MARIOBASZ** [comment]
@Harvie, where do I find how to write module options?

**Comment by MARIOBASZ** [comment]
trochoid path now allows you to place z objective and steps as done with cut (I do not know why, but it is only valid for z <0).
Trochoid 3d is now executed with a single click (generates trochoid path, modifies it to z objective and then on this route generates helical descent and trochoids)

**Comment by Harvie** [comment]
To get up to date, you can use this https://github.com/MARIOBASZ/bCNC/pull/1

**Comment by MARIOBASZ** [comment]
Thanks, even though it seems silly, I do not know how to update my branch (I do not know how to open the command console on github ....)
I have pressed the button that you have given me and my branch was updated correctly.
I hope you can upload the plugin.
I have partially advanced in generating the traditional final cut to rectify after the trochoidal milling, I have not been able to advance in the generation of tabs / islands

**Comment by Harvie** [comment]
> (I do not know how to open the command console on github ....)

There is no command console on github. There is comand console on your computer. You install software called git and you can use it to upload/download changes directly from your work directory on your computer without having to do it on website all the time.

> I hope you can upload the plugin.

I can. But can you please first add `self.help` explanation of how to use the plugin?

**Comment by Harvie** [comment]
Perfecto! :-)

image

**Comment by Harvie** [comment]
This is how you clone your repository to your computer using git. Then you pull from vlachoudis and push to mario:

image

(it says "permission denied", because mario is not mine... it will work for you, if you upload your ssh key to github)

**Comment by MARIOBASZ** [comment]
Thank you! Could you integrate adaptive to your trochoid?
Can you solve the tabs and the termination (does not work in linked blocks) in my version? Now that I remember, this will improve after uploading it, but you know that I supplant with missing knowledge. I can upload the changes if it helps. It would be a more complete application with these details. Sometimes the little help frustrates me, intuiting that there are those with knowledge who will find it easy to solve it: it takes me a long time to make each contribution, of course it is a personal satisfaction, for the same value or what you do and the rest for free and with the courage to contribute to strangers

**Comment by Harvie** [comment]
I've hidden trochoid path to development and updated icons:

image

**Pull request merged**
