### PR TITLE
add 5s pause after tool change

### PR DESCRIPTION
**Pull request by leofaoro**
to allow spindle to speed up

### CODE REVIEW

**Comment by sfinexer** [comment]
https://github.com/vlachoudis/bCNC/issues/1102

**Comment by Harvie** [comment]
Thanks!
If you manage to add some UI to make this optional, it would be even better.
Isn't 5s too much? VFD spindle starts typicaly around 2 seconds, so 3 seconds should be enough.

BTW have you tried enabling pause after toolchange?

image

It might have similar result...

**Comment by Harvie** [comment]
Also congratulations for your first commit merged to bCNC :-)

**Comment by leofaoro** [comment]
> Also congratulations for your first commit merged to bCNC :-)
Thanks @Harvie ! I am learning python and how to contribute here. Hopefully many more to come!

I haven't tried this no proble manual tool change, it's not something I use. I really only use the WCS option.

**Comment by Harvie** [comment]
I am not talking about "no probe", i am talking about "pause before and after probing"

**Pull request merged**
