### PR TITLE
Increase Stability of Pocket with Islands Plugin

### PR DESCRIPTION
**Pull request by DodoLaSaumure**
After furhter tests, I have found that these changes increase stability of the plugin pocketswithislands.
Pierre

### CODE REVIEW

**Comment by Harvie** [comment]
Thank you

**Comment by Harvie** [comment]
Actualy the bCNC does not even start with these modifications:

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/harvie/Temp/bCNC/bCNC/__main__.py", line 2729, in <module>
    main()
  File "/home/harvie/Temp/bCNC/bCNC/__main__.py", line 2696, in main
    application = Application(tk)
  File "/home/harvie/Temp/bCNC/bCNC/__main__.py", line 117, in __init__
    self.tools = Tools(self.gcode)
  File "/home/harvie/Temp/bCNC/bCNC/ToolsPage.py", line 1100, in __init__
    tool = eval("%s.Tool(self)"%(name))
  File "<string>", line 1, in <module>
  File "/home/harvie/Temp/bCNC/bCNC/plugins/pocketwithislands.py", line 327, in __init__
    ("CustomRecursiveDepth","int",1,_("Nb of contours (Custom Recursive Depth)max"+str(sys.getrecursionlimit()-1))),
NameError: name 'sys' is not defined
```

**Comment by DodoLaSaumure** [comment]
Thank you Tomas.
I do not know why, but the code worked for me both with py2 & py3 without the import sys.
Going to check.
Pierre

**Comment by DodoLaSaumure** [comment]
It seems to be new in  python3.9 I do not know why, I found no explanation on the web, if someone has an explanation, I am interested.
Pierre

**Comment by DodoLaSaumure** [comment]
Hey I ve got it 
#1481

tkinter dropped sys in 3.9

**Comment by Harvie** [comment]
Please note this commit: https://github.com/vlachoudis/bCNC/commit/1d872e0e2e04568c158226ee0fe68842e530e04b

I've renamed your plugin and started polishing things up, so it can replace core functionality soon.

**Comment by DodoLaSaumure** [comment]
> Please note this commit: 1d872e0

Hey !! Great !! ;)

**Comment by Harvie** [comment]
I went even further and cleaned up the GUI significantly... It was too messy.

image

**Comment by DodoLaSaumure** [comment]
Congratulations !! I am going to try the new GUI ;)

**Pull request merged**
