### PR TITLE
Pocket islands plugin

### PR DESCRIPTION
**Pull request by DodoLaSaumure**
try to merge profile, pocket, pocket with islands into a single experimental plugin

### CODE REVIEW

**Comment by DodoLaSaumure** [comment]
@Harvie 
I have not added yet the extra segments to cover 100% of the pocket in all cases (uneven lines problem with stepover > 50%)
But I think it covers all the other points that we reviewed in #1536.
I have done some tests, for me it appears to be ready to be merged in head. 
Please make some further tests if you want to be sure.
Pierre

**Comment by Harvie** [comment]
There is bug in offset direction and overcuts.

This is original profile tool in bCNC (inside+overcut):

image

This is your plugin (inside+overcut=1):

image

Your plugin (outside+overcut=1):

image

So you can see the direction is inverted and overcuts do not work.
Please make overcut as checkbox rather than numeric input. (is there any benefit from this?)

Also see how offset direction (inside/outside) works in original code. We had similar problem in there. If i remember corretctly the solution was to normalize the path direction (CW/CCW) to be same in all cases. Then it was easy to get consistent switching between inside/outside profiles.

**Comment by Harvie** [comment]
OOOH. I understand now.
You've confused "overcuts" and "additional offset distance". This is what seems to cause the issues.

Overcuts are these tiny pieces of path that allow to cut all the way into the corners so you can avoid corners being rounded and fit square peg into the square hole:

image

It is very important!

image

**Comment by DodoLaSaumure** [comment]
> You've confused "overcuts" and "additional offset distance".

ah ok, yes I confused these two things.
Going to fix it soon
Pierre

**Comment by DodoLaSaumure** [comment]
In this case, it is not exactly an additional offset distance (it is substracted from the offset), it is a correction for correcting the path tolerances (like a tool correction)
it's very important too, to be able to adjust the tolerance of a profile.

**Comment by DodoLaSaumure** [comment]
I would name it "additional distance inside profile", I think that's more clear to all.
Pierre

**Comment by Harvie** [comment]
Thank you... So far i was not able to find any issue.
Only thing that comes to my mind is ignoring the islands:

1.) Add checkbox "ignore islands", so users can easily get back the original behaviour
2.) By default ignore all islands marked as "tab"... I see very little point in affecting profiles and pockets by tabs. These will be handled in cutting operation anyway...

**Pull request merged**
