### PR TITLE
midi2CNC

### PR DESCRIPTION
**Pull request by Effer**
Ok, sorry but I didn't resist.
Here the more useless plugin ever, use you cnc as a musicbox with the port midi2cnc to bCNC.
Load a midi file, set up your pulse per unit and listen you machine play your favorite song.

midi2cnc

I've tested with some midi file and results are fun.

My cnc is simply to ugly to public a video,but @carlosgs perhaps you would like to make one?
And @vlachoudis  I understand if you do not want to add this to bCNC becouse is too silly, but it worth a try.

Most of the work had to be credit to https://github.com/michthom/MIDI-to-CNC as they release the code as public.

### CODE REVIEW

**Comment by chamnit** [comment]
@Effer : HA! This made my day. Thanks for sharing this.

**Comment by vlachoudis** [comment]
On the contrary it is fun. I like it.

**Comment by Effer** [comment]
Thanks @chamnit ! It wouldn't be possible without grbl and @vlachoudis bCnc.
I really enjoy this experience.

**Comment by carlosgs** [comment]
<https://www.youtube.com/watch?v=Zg9FbhsxJDY> :-P

**Comment by atrueresistance** [comment]
https://www.youtube.com/watch?v=gCjTCCysMcA

**Comment by vlachoudis** [comment]
The entertainer :)
https://youtu.be/0omkq_WVUyY

**Comment by atrueresistance** [comment]
Upped the acceleration for all axis to 500. Seemed ok.
https://www.youtube.com/watch?v=fydofLgnchw

**Comment by Effer** [comment]
Congratulations @atrueresistance sounds much better.
Here in the wiki https://github.com/vlachoudis/bCNC/wiki/Midi2CNC I've added this performance, feel free to improve it with yours experience and suggestions.

**Pull request merged**
