### PR TITLE
Added plugin for simple bowl generation

### PR DESCRIPTION
**Pull request by carlosgs**
I saw this feature in a commercial CNC software a while ago, and thought it would make a nice demo:

screenshot from 2015-09-14 17-08-12

### CODE REVIEW

**Comment by carlosgs** [comment]
Oh and I'm liking the simple API a lot!

**Comment by carlosgs** [comment]
Here is a test of the bowl function. The parameters it uses internally are tool diameter and zstep.

screenshot from 2015-09-14 20-05-33

Video: https://www.youtube.com/watch?v=y6eOiGU3GBE (loud!)

img_20150914_194955

img_20150914_195846

It is the first thing I've milled with bCNC. Thanks again for this software!

**Comment by vlachoudis** [comment]
Fantastic! I like that people already started using the new features. I will merge it tomorrow afternoon after work. Just one correction, please use the addUndo method when inserting the code (see the gear plugin) to enable the undo mechanism. The 32px icon is not necessary.

**Comment by chamnit** [comment]
@carlosgs : That is way cool. Great job.

**Comment by carlosgs** [comment]
Hmm... can't find the addUndo method in the gear example. But undo is working fine anyways! :)

"I like that people already started using the new features."  
Fun fact, I downloaded and tried bCNC for a few minutes, then ran "git pull" and the interface was suddenly changed and looking amazing :+1: it was nice timing! ^_^

**Comment by vlachoudis** [comment]
Sorry forget my comment on undo. I forgot that I added the insBlocks method that does the undo as well :)

**Pull request merged**
