### PR TITLE
Major tab fix! Center drilling, Centerpoint plugin, Improved trochoids, Single click DRO zero, Oneshot plugins, Flatpath plugin, Helix recut, Plugin icons on exe button

### PR DESCRIPTION
**Pull request by Harvie**
Centerpoint plugin. Useful for drilling in middle of shapes (eg.: circles):

image

This is implemented as completely new kind of plugin (`self.oneshot=True`), which does not show menu with options on the left, but rather executes immediately after clicking on the icon.

Also added this as option to drill op:

image

Trochoids now continuous #815 :

image

Single click zeroing:

image

Plugin icon on execute button:

image

### CODE REVIEW

**Comment by MARIOBASZ** [comment]
Good progress!!!!!!

**Comment by Harvie** [comment]
@walterwissmann you're welcome. It's my hobby and i am happy to bring new CAM possibilities to Linux.

**Comment by walterwissmann** [comment]
@Harvie 
Where can i find your changes to test it?

**Comment by walterwissmann** [comment]
lol, now i am here ;) Ok. 

I installed the version of your bCNC on a RasPi 3. It work's great.

I found:
Tab function on a little piece work not fine, on a great piece fine.
I created a little clamp for a camera in LibreCAD
Make a outline profile
generate three tab's with the tab function
then cut it with the cut function with a cross on 'Leave islands uncut'.
The result is: one of the tabs are fine, The rest not there... 
image

Or when i take the tab's to an other place:
 image

Tab parameter:
MinDistance: 0.0
Dx: 1.0
Dy: 1.0

[XY_Camerahalter.txt](https://github.com/vlachoudis/bCNC/files/2281001/XY_Camerahalter.txt)

**Comment by Harvie** [comment]
@walterwissmann It's not related to this pull request, since i didn't changed anything related to tabs since last pull request, but I'll take a look at it. It's almost surely my fault, because i've completely rewriten the tab code in the past. Can you please create new issue with this description?

**Comment by Harvie** [comment]
@walterwissmann aha. sorry. i am taking it back. this PR actually kills the tabs. i have to fix it before it gets merged. As workaround for now you can select tabs in editor and click on split:

image

**Comment by Harvie** [comment]
@walterwissmann should be fixed now

**Comment by walterwissmann** [comment]
ok. i test it now...

**Comment by walterwissmann** [comment]
It is the same:
image

Editor:
image

I will test it also with a 1cm x 1 cm square...

**Comment by walterwissmann** [comment]
I have test it with four squares 1x1, 2x2, 3x3, 10x10 cm squares in one File without splitting:
( I hope it help a little bit to find the bug... )

[Quadrate.txt](https://github.com/vlachoudis/bCNC/files/2281387/Quadrate.txt)

image
image

**Comment by Harvie** [comment]
@walterwissmann i've found the culprit. isInside() method in lib/bpath.py is not working correctly.

**Comment by Harvie** [comment]
@walterwissmann at least i've came up with workaround. you can try it now.

**Pull request merged**
