### PR TITLE
Some useful plugins and bugfixes (python3 support)

### PR DESCRIPTION
**Pull request by DodoLaSaumure**
There are plenty of beautiful, funny useless plugins on bCNC.
I would like to add some basic features such as creating a simple rectangle, line, circle, drill, and being able to copy-cut translate copy-cut rotate

### CODE REVIEW

**Comment by DodoLaSaumure** [comment]
The new plugins are available in the Tool page, CAM/generator subbmenu
I have tried to put them in the editor page by creating a menu in the Transform group, but the left pannel is already occupied by the code editor, and I would not like to change this.
Maybe there is a better place to put SimpleTranslate / SimpleRotate, but I do not see where to put these menus, since there is not so much room available.
Happy new year to all.
Pierre

**Comment by Harvie** [comment]
Hi. Happy new year and thanks for contribution.
I will take a look at your plugin addition, but at the first glance i have feeling like some of these plugins might to some extent duplicate functionality of already present plugins.

For example. We have already this situation with three driller tools in bCNC. None of them can do all things well. So i would be VERY hesitant to add 4th drilling tool. I want to merge these to single plugin. As it's very confusing to newcoming users of bCNC...

But i haven't checked your code in its entirety...

**Comment by DodoLaSaumure** [comment]
Hello Thomas.
Happy new year to you and your family.
Thank you for reviewing. I understand your hesitation for the drilling tool. You are right, it duplicates existing tools and maybe we could improve and optimize existing ones before creating duplicates.

My concern about drilling is to be able to drill at any position from no existing object, and optimize machining time

For the other tools, I did not find any way to create basic patterns, and copying and rotating them.
But maybe I missed something. 

Thanks for reviewing
All the best 
Pierre

**Comment by Harvie** [comment]
> For the other tools, I did not find any way to create basic patterns, and copying and rotating them.
But maybe I missed something.

Editor menu:

image

CAM menu:

image

What about these?

**Comment by DodoLaSaumure** [comment]
Yes Thomas I saw these tools, but in my point of view ( maybe I missed something)

- Move allows user to move a block graphically, but not with a given dx dy
- Transform tools allow user to rotate objects by 90° increments only
- Tile tool allows user to tile a pattern in x y simultaneously, along x axis OR y axis ( but not translate from dx,dy)

I would like to be able to copy paste an object 
- rotation by  step angle ( multiple copies allowed)
- Translation by (dx dy), mutliple copies allowed

Maybe we can modify the tools you mention, but I think they are not dedicated to this use.
Feel free to review my code, modify it or improve it at your convenience.

All the best
Pierre

**Comment by DodoLaSaumure** [comment]
@Harvie 
In fact, I would like to be able to achieve this directly from bCNC, without importing any dxf, in two clicks

image
or this
image
or this
image

**Comment by MARIOBASZ** [comment]
I am interested in reading what you have written.
As usual, maybe I didn't understand correctly ...
From the command line you can rotate a block the angle you want.
I agree, unifying perforations is a good idea.
Perhaps it is a good decision to implement that from drilling it generates holes larger than the diameter of the milling cutter:
the angle of helical descent can be generated automatically by relation (for the material) between velocity xy / velocity z

**Comment by DodoLaSaumure** [comment]
@MARIOBASZ 
Thank you MarioBasz for the command line tip
 the code can be checkout / Cloned from this fork
https://github.com/DodoLaSaumure/bCNC

From what I have seen, the command line does not allow (until now) mutliple copies. Maybe a graphical tool is more intuitive, but that is just my point of view
All the best
Pierre

**Comment by MARIOBASZ** [comment]
You're right Pierre, lets turn. create rotated copies in two click sounds interesting

**Comment by DodoLaSaumure** [comment]
@MARIOBASZ 
I appreciate that you appreciate ;-)

> Perhaps it is a good decision to implement that from drilling it generates holes larger than the diameter of the milling cutter:
> the angle of helical descent can be generated automatically by relation (for the material) between velocity xy / velocity z

I am not sure to understand what you precisely mean.

**Comment by MARIOBASZ** [comment]
I mean generating holes, not just drilling, Maybe it's not a good idea to unify many things, maybe keep as separate plugins and modify helical to perform multiple perforations or multiple threaded, copy anchor mode is an option

**Comment by DodoLaSaumure** [comment]
@MARIOBASZ 
Ah OK Mario, understood. In fact I did not want to be intrusive in the original source, and I kept separate plugins, that are more easy to maintain, activate or desactivate.
But as @Harvie  says, we must keep in mind not to multiply the same tools in different parts of the code.
Best regards
PIerre

**Comment by MARIOBASZ** [comment]
I haven't seen it yet, adding simple polygon can be useful.
add simple spiral maybe too (can it be useful for future pocket operation?)
I think that in trocoidal 3d is used, more neat would be to separate it

**Comment by MARIOBASZ** [comment]
Interesting, I've looked at simple arc and simple denim.
This would improve you to simple denim:
- if you do not set z safe, the default is the default (material)
- if you do not set speed z, it is the default (material)

- Only for thoroughness and less writing, there is a value g1z (intermediate f) that can be eliminated:
image

this:
g1 z-2 f200
g1 z-4 f200

Consultation due to ignorance: waiting time, pecking, is usually placed when the tool is inside the material, or when it is safe?
In my opinion, this type of efficient descent should be included as a downward movement. In my machine I am using it like this:
1-From safe Z to Surface + minimum safety distance (0.5mm / 1mm?) G0 speed
2-up Surface at half speed (smooth tool tip punch against material)
3-continue at normal speed
I avoid a lot of useless time since safe z = 30mm going down to F200

**Comment by MARIOBASZ** [comment]
Pierre , @DodoLaSaumure 
Thanks for your plugins!
I am in the development of two projects with a low cost idea:
1- a vacuum table that allows to continue even after making holes (for example for pcb)
2- an automatic tool changer
I have already used your simple drill and it would have been very nice simple rectangle with rounded corners.
Hugs.

**Comment by MARIOBASZ** [comment]
To avoid collisions with clamps, the last movement would make G0 z safe

**Comment by DodoLaSaumure** [comment]
Thank you very much  Mario for sharing your experience. I appreciate it very much and I am happy if these plugins are useful to someone.
Again my idea is to share basic plugins for easy creation of primary paths. Then user can use these patterns to create whatever he wants cut, pocket, profiles, attaches, etc..all the features already available in bCNC
image


Going G0 under the surface for drilling (where the material has already removed) is common in professional machining, as far as I know, to optimize machining time, but I am not an expert.

Pierre

**Comment by MARIOBASZ** [comment]
Pierre, would you like to collaborate to finish a complement to optimize milling with two different diameter milling cutters, thick roughing on one side and access to angles and areas where it does not reach the other, useful for pcb or signage, for example?
I have advanced a lot, but my programming knowledge is less than elementary, performing each step demands a lot of time.
The main problem that occurs in this developing plugin is the time it takes to process.
Maybe directory or set instead of tuples speed up the process? Arrangements?

**Comment by Harvie** [comment]
@DodoLaSaumure i understand that you miss some features in the tools already present in the bCNC. But imagine the confusion of newcoming users when we have multiple tools that all do seemingly similar thing. We need to integrate these.

For example: bCNC already has 3 different plugins for drilling holes! How do i explain this to newbies? It's simply unjustifiable.

I think it's good idea to remove some of the integral tools from bCNC core and re-create them as separate plugins, so they can be easily merged and adapted for new use cases. Currently there are several cathegories of plugins under the CAM tab. We might need to add new cathergories of plugins which will integrate with the Editor tab in similar manner.

**Comment by MARIOBASZ** [comment]
Personal experience:
Simple Arc and Simple rectangle I use them a lot.
Simple Rotate was also very helpful in a project.

**Comment by Harvie** [comment]
Is this PR still relevant after merging #1405 ?

**Comment by DodoLaSaumure** [comment]
@Harvie 

Hey Tomas
I am realizing that this pull request has been merged by my mistake on the head.
This is because I upgraded my master fork to the upstream of vlachoudis/bCNC, and then merged to my fork patch-4. My master fork already had those commits.

So I am going to close this PR
Next steps for me are 
- split the menus into different categories under the CAM tab
- Trying to rationalize redundancies between the different tools (Drill, move, etc..)

following your recomandations

> @DodoLaSaumure i understand that you miss some features in the tools already present in the bCNC. But imagine the confusion of newcoming users when we have multiple tools that all do seemingly similar thing. We need to integrate these.

> For example: bCNC already has 3 different plugins for drilling holes! How do i explain this to newbies? It's simply unjustifiable.

> I think it's good idea to remove some of the integral tools from bCNC core and re-create them as separate plugins, so they can be easily merged and adapted for new use cases. Currently there are several cathegories of plugins under the CAM tab. We might need to add new cathergories of plugins which will integrate with the Editor tab in similar manner.

**Comment by Harvie** [comment]
> I am realizing that this pull request has been merged by my mistake on the head.

Yes. I've noticed some of it. Please make sure that no unfinished or buggy code got into vlachoudis master during this.

**Comment by DodoLaSaumure** [comment]
@Harvie 
Hi Tomas
> Please make sure that no unfinished or buggy code got into vlachoudis master during this.

I understand your concern on bugs on bCNC
My view is that bugs are the essence of coding.
When you write a software, you are pretty sure you'll find some bugs one day or another. Open source and Agile allow continuous improvements on the code.

I have been using these tools a lot along the past year, and did not find bugs or corrected them. I find these tools very useful, not because they are "mine", but because you can create basic shapes inside bCNC, move and rotate them as you want. It is sometimes very useful to do that, allowing the user to create simple patterns, without any CAD.
There is no major risk for the user, since he can see the pattern created in the interface, before machining.

For the drilling tool, user has to be aware that this tools allows making g0 moves under the surface, inside the already drilled material, in order to improve machining processing. This tool is useful to accelerate machining, when you have plenty of drills to do. From my point of view there is no major risk for the user in doing that.

I am aware that is redundant with some other tools, and I can remove it now if you want and give us some time for thinking about this.

Please tell me your view.
Have a great end of year
Pierre

**Comment by DodoLaSaumure** [comment]
PS : In addition to the previous comment
- SimpleDrill tool allow drilling in any x,y position, which is not provided by the other drilling tools, and seems to me to be a basic operation that a drilling tool should do
- there are warnings for the user about the G0 moves under the surface, with safe default options. As an improvement, we could add a pop up warning when entering a negative value for "safe z secu for G0" field.


Pierre

**Comment by Harvie** [comment]
> SimpleDrill tool allow drilling in any x,y position, which is not provided by the other drilling tools, and seems to me to be a basic operation that a drilling tool should do

And our job is to invent streamlined user interface to cover all common use cases in nice useful tool. Otherwise we will deter users and therefore new developers from bCNC project.

> Open source and Agile allow continuous improvements on the code.

Yes, the travis tests are kinda disabled right now because something has changed in upstream. :-) Help is welcome...

**Comment by Harvie** [comment]
BTW have you seen this feature i've added some time ago?

image

You can already drill or cut at any points using this... By entering arbitrary coordinates, or even jogging to the point and recording it, which allows for handy interactive machining workflow.

**Comment by Harvie** [comment]
But you have to select all recorded points and apply drill operation on them in order to do actual drilling. But you can do that for all selected points at once.

**Comment by DodoLaSaumure** [comment]
> Yes, the travis tests are kinda disabled right now because something has changed in upstream. :-) Help is welcome...

I have to confess I do not know anything about Travis

> BTW have you seen this feature i've added some time ago? You can already drill or cut at any points using this... By entering arbitrary coordinates, or even jogging to the point and recording it, which allows for handy interactive machining workflow. But you have to select all recorded points and apply drill operation on them in order to do actual drilling. But you can do that for all selected points at once.

I did not notice this tool. And I do not understand how I can enter the position of the points? I can see how we jog to a point and record it (I have not read the code yet)

All the best
Pierre

**Comment by Harvie** [comment]
> And I do not understand how I can enter the position of the points?

Just enter the coordinates (or eval formula) to WPos and hit enter:

image

**Comment by MARIOBASZ** [comment]
I have not experienced your simpledrill. For multiple drilling I choose Anchor within driller.
In personal use, I have added a zenter_rapid (I also use it when doing cut):
1- Descend as G0 to Z surface +1
2- Continue at grating speed.
In pecking, it descends rapidly to 1 higher than the previous pecking and then slowly.
Note: you have to modify the plugin: the first drill is done in a previous location where it should start, unless I am making a mistake.
I am also using with a modification to make holes and threads in addition to holes, however perhaps it is better for practicality than to use anchor inside Helix_ descent, and divide this plugin into 3:
Holes
Threading
Countersunk / cone

**Comment by DodoLaSaumure** [comment]
@Harvie  @MARIOBASZ 
Thanks Thomas and Mario, I am going to have a look one of those days.
Have a great evening in this special day.
Pierre

**Comment by Harvie** [comment]
Happy new year.

**Comment by DodoLaSaumure** [comment]
.;;,     .;;, 
          `  ;;   ;;  ' 
             ;;   ;; ,  .;;;.   .;;,;;;,  .;;,;;;,  .;;.  .;;. 
            ,;;;;;;;;;'  `   ;;  ` ;;   ;; ` ;;   ;; ` ;;  ;; ' 
           ` ;;   ;;    .;;.;;    ;;   ;;   ;;   ;;   ;;  ;; 
             ;;   ;;    ;;  ;; ,  ;;   ;;   ;;   ;;   ;;  ;; 
          .  ;;    ';;' `;;;';;'  ;;';;'    ;;';;'     `;;'; 
          ';;'                    ;;        ;;            ;; 
                      .  ;;     .  ;;         .  ;; 
                      ';;'      ';;'          ';;' 
         
               .;;, ,;;;, 
               `  ;;    ;; 
                  ;;    ;;     ,;;,  .;;.      .;;, 
                  ;;    ;;    ;;  ;; ` ;;      ;; ' 
                  ;;    ;;    ;;;;;'   ;;  ;;  ;; 
                  ;;    ;;    ;;   .   ;;  ;;  ;; 
               .  ;;     ';;'  `;;;'    `;;'`;;' 
               ';;' 

                              .;;.     .;;. 
                              `  ;;   ;;  ' 
                                 ;;   ;;   .;;,  .;;;.   .;;.;;;, 
                                 ;;   ;;  ;;  ;; '   ;;  ` ;;   ' 
                                 ;;   ;;  ;;;;;' .;;,;;    ;; 
                                  `;;;';  ;;   . ;;  ;; ,  ;; 
                                      ;;   `;;;'  `;;';;'  ;' 
                                      ;; 
                                  .'  ;; 
                                  ';;;'

**Pull request closed without merging**
