### PR TITLE
Mouse position display in inches #45

### PR DESCRIPTION
**Pull request by Effer**
Make some test and  it work in inch now.
I've not look in deep if was better to change the output from canvas2xyz(). That is used in many others parts that works already in well.

### CODE REVIEW

**Comment by Effer** [comment]
I've notice a small defect in the two label on the bottom of bCNC. When moving coordinates with mouse the two widgets resize himself in an erratic way. You .pack them, but maybe using .grid could avoid the flicker.

**Comment by vlachoudis** [comment]
@Effer I would like to merge part of the pull requests, but the system doesn't allow me. Do you know how I can select which commits I could merge

**Comment by Effer** [comment]
I'm new to git too, so take with caution

**git cherry-pick "hash commit number"**

Extracted from:
http://markosullivan.ca/how-to-handle-a-pull-request-from-github/

You should clone my report and the check out it. Go to your branch and cherry-pick the interessted commit. If in doubt copy & paste  what you need ;)

**Comment by Effer** [comment]
A passage was missing, you also had to add my repository as remote and fetch it. From then you can cherry-pick the commit you need.

http://stackoverflow.com/questions/5120038/is-it-possible-to-cherry-pick-a-commit-from-another-git-repository

**Pull request closed without merging**
