### PR TITLE
10 new text chains translated in french (4th commit)

### PR DESCRIPTION
**Pull request by ThierryM**

### CODE REVIEW

**Comment by vlachoudis** [comment]
Hi @ThierryM one correction is the "round" (From the "Editor/Edit/menu->Round") should be translated as "arrondi" is the function to round the decimal digits in the gcode

**Comment by ThierryM** [comment]
Hi,
I don't see the menu :  
selection_039

**Comment by carlosgs** [comment]
It should be "Arrondi" rather than "Diametre"

**Comment by ThierryM** [comment]
Le 20/01/2016 21:05, Carlos Garcia
      Saura a écrit :
    
    It should be "Arrondi" rather than "Diametre"
    
    Thanks.
    
      
      On Wed, Jan 20, 2016 at 8:52 PM, ThierryM
      <notifications@github.com> wrote:
      
      > Hi,
      > I don't see the menu :
      >
      > [image: selection_039]
      >
<https://cloud.githubusercontent.com/assets/1470067/12461074/4f63c92a-bfb7-11e5-8d6d-551696356a06.png>
      >
      > —
      > Reply to this email directly or view it on GitHub
      >
<https://github.com/vlachoudis/bCNC/pull/204#issuecomment-173339508>.
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Pull request merged**
