### PR TITLE
3D mesh slicing! Improvements on islands, Tabs are now editable islands too, CAMotics compatibility, Major trochoid improvements, Join/Split blocks!, Fixed move of G91

### LINKED ISSUE #915: G91 problems when moving or otherwise modifying
When having block like this utilizing G91 it will fall apart when moved:

```gcode
(Block-name: block)
(Block-expand: 1)
(Block-enable: 1)
g0 x0 y0
g1 z0
g1 x10 y0
g91
g1 x0 y10
g1 x-10 y0
g90
g1 x0 y0
g0 z10
```

This is kinda fun, because you can make blocks that will change shapes when moved. However it's not really practical for CNC use:

image

This is due to the fact that coordinates between G91 and G90 are translated too. bCNC should stop modifying coordinates after G91 and resume after G90 when moving block.

I am not really sure if this bug also affects other operations.

BTW Fixing this might make hand editing of tabs even more user friendly, since it will be needed to edit only 1 segment instead of 4 if we'll use G91 to describe tabs.

### PR DESCRIPTION
**Pull request by Harvie**
Improvements from https://github.com/harvie/bCNC

image

I simplified the use of islands. now you don't need to create tab object from islands, you can directly cut... #220 

image

image

Smoother trochoidal mode #815  Also supports arcs now :-)

image

Tabs are now implemented using islands #912 

image

Trochoidal in combination with tabs and camotics :-)

image

Join blocks together and split them again :-) Useful for modifiing individual tabs! #912 
Fixed #915 

image

Optional circular tabs to get consistent tab size over lines with various angles

image

image

New plugin can slice 3D meshes in STL and ASCII PLY format! #901 
Now we have two modes.

image

Non flat:

image

Flat:

image

### CODE REVIEW

**Comment by MARIOBASZ** [comment]
Hi, I have detected this problem when trying to use islands in pocket operation: sometimes it cuts inside the island instead of keeping Z safe

image
Here it happens
image
Not here
image

I think it would be good if Z is safe to move with G0 (I only made a partial modification when entering the island)

**Comment by MARIOBASZ** [comment]
If it is viable, it would be that you ignore the movements (ectors or points) when you are traveling within the island
Another idea: you can make a union of islands, and that results only the perimeter of the unions, but eliminating the intersection of them (what resuta of your operation difference)
We would be one step closer to make a more efficient PCB routing

**Comment by MARIOBASZ** [comment]
I have seen that in the implementation already uploaded to the master branch, in the cut operation the heights in and out of tabs do not work well.
I leave the question here or do I upload it as a neva issue?

**Comment by Harvie** [comment]
@MARIOBASZ it seems to me that you do not use latest version from my fork, i've already fixed these issues. @vlachoudis did not merged my latest fixes yet, so there are still some bugs related to islands in upstream repository. Not sure what takes so long, perhaps @vlachoudis and @buschhardt are on vacation :-)

**Comment by Harvie** [comment]
I see there's some controversy about licencing. is that reason why merging takes so long?

Just to make things clear:

This pull request introduces some code that is BSD and MIT licensed. Both of these are GPLv2 compatible. But i needed to add files indicating that the code was originaly BSD/MIT and was sublicensed as GPLv2. (You can use BSD and MIT code in GPLv2 project as long as you let everybody know about origin of that code and it's original license, which is what i've done here)

**Comment by Harvie** [comment]
@vlachoudis i am concerned about my work as @MARIOBASZ works on the same code and the conflicts start appering. We need to synchronize in upstream to prevent this. I don't really care about licensing of my code as long as it will be free. We can figure this along the way, it's not that hard. I know we reuse some 3rd party code, but that can be solved also. Usualy opensource guys want their code to be as usefull as possible and various licenses are just tools to achieve that. It's not written in sone.

Can you please look at this? It's been almost month. I've broken some stuff in the past and this pull request fixes that, so i feel bad when it's left unmerged. If you have any concerns about the code quality, feel free to discuss it.

I used to be very enthusianistic about working on bCNC, but this heavily demotivates me. I am sorry to rush this, but i don't want to run in git conflicts and have to manualy rework my code. I know that you are not working on bCNC full time, so you have other stuff to do, but the cooperation between contributors is kinda hard if you don't pull regulary.

Once again sorry for rushing this and let me know if you need to help with something! :-)

**Comment by vlachoudis** [comment]
Many thanks, there is a lot of work done here!

**Pull request merged**
