### PR TITLE
System colors customization

### PR DESCRIPTION
**Pull request by ptvoinfo**
System colors customization (very useful for dark Ubuntu system themes).

### CODE REVIEW

**Comment by Harvie** [comment]
Can you please add some screenshots to explain what this does?
I've tried running it on XFCE with dark theme, but the bCNC UI is still in light colors.

**Comment by ptvoinfo** [comment]
This problem is mentioned here (with the screenshot): #450, #1238 

The main problem is text in edit fields (white text on white background):
My screenshots (before/after with customized colors):

img1
img2

**Comment by Harvie** [comment]
Thanks. I've merged it, but we still need to test it on other platforms. Eg. Windows.

**Comment by ptvoinfo** [comment]
Sure. Therefore, The default INI file contains empty values. In this case, my update does not change anything. It'll take effect only if a user defines a color.

**Pull request merged**
