### PR TITLE
camera-fix

### PR DESCRIPTION
**Pull request by Effer**
Without this, camera doesn't show in the canvas in my pc.

### CODE REVIEW

**Comment by vlachoudis** [comment]
Thanks. On linux it was working Ok, I don't understand why windows fails.
I've move it after the check on the camera for None.
However it should be better to be after the self.set()
and maybe a call on the "self.read()" instead to process the image as well

**Comment by Effer** [comment]
To be honest I didn't dig too much. I remembered the camera was working some versions ago. Yesterday I made a small test and no picture was show in the canvas.
For sure the call should be done after the None test, but strange enough call to self.read() doesn't work. Neither after self.set(). No errors BTW, simply no images. I suspect the camera.isOpened() method have some differences in windows.

Off topic: that self.matchTemplate() looks interesting. Some time go I was testing an automatic zero reference based on a glyph placed on stock material.. First tests were not promising.

**Comment by vlachoudis** [comment]
matchTemplate() I used it to calibrate the camera vs workspace, however mine has a big distortion so I didn't get nice results. First I need to calibrate the camera with a checker pattern and then I would be able to use the matchTempalte()

**Comment by Effer** [comment]
I was testing with SIFT and FlannBasedMatcher. Quite slow and unstable. But a funny CV experiment.

**Pull request closed without merging**
