### PR TITLE
Update fake-grbl-arduino.ino

### PR DESCRIPTION
**Pull request by sfinexer**
Having looked that gives out GRBL in the code lacks the response "OK".

### CODE REVIEW

**Comment by Harvie** [comment]
I don't think that GRBL sends `OK` in response to `?` command

**Comment by sfinexer** [comment]
@Harvie Video:
http://cnc.tiven.ru/ssr-2019-02-19_08.13.52.mp4

**Comment by Harvie** [comment]
See this log made using pyserial `spy://`. I don't see any OK reply for `?` command sent by GRBL:

```
?<Idle|MPos:0.000,0.000,0.000|FS:0,0|Ov:100,100,100>
?<Idle|MPos:0.000,0.000,0.000|FS:0,0>
?<Idle|MPos:0.000,0.000,0.000|FS:0,0>
?<Idle|MPos:0.000,0.000,0.000|FS:0,0>
?<Idle|MPos:0.000,0.000,0.000|FS:0,0>
?<Idle|MPos:0.000,0.000,0.000|FS:0,0>
?<Idle|MPos:0.000,0.000,0.000|FS:0,0>
?<Idle|MPos:0.000,0.000,0.000|FS:0,0>
?<Idle|MPos:0.000,0.000,0.000|FS:0,0>
?<Idle|MPos:0.000,0.000,0.000|FS:0,0|WCO:-3.236,0.430,-1.587>
?<Idle|MPos:0.000,0.000,0.000|FS:0,0|Ov:100,100,100>
?<Idle|MPos:0.000,0.000,0.000|FS:0,0>
?<Idle|MPos:0.000,0.000,0.000|FS:0,0>
?<Idle|MPos:0.000,0.000,0.000|FS:0,0>
?<Idle|MPos:0.000,0.000,0.000|FS:0,0>
?<Idle|MPos:0.000,0.000,0.000|FS:0,0>
?<Idle|MPos:0.000,0.000,0.000|FS:0,0>
?<Idle|MPos:0.000,0.000,0.000|FS:0,0>
?<Idle|MPos:0.000,0.000,0.000|FS:0,0>
?<Idle|MPos:0.000,0.000,0.000|FS:0,0|WCO:-3.236,0.430,-1.587>
?<Idle|MPos:0.000,0.000,0.000|FS:0,0|Ov:100,100,100>
```

**Comment by Harvie** [comment]
The reason why you get `ok` from grbl is because you don't send `?` the arduino ide actually sends `?\n`. Know the difference.

**Comment by sfinexer** [comment]
Then send a fake-grbl-arduino.ino long G-cod and verify that the buffer is full.

**Comment by Harvie** [comment]
Because you are sending `?` using terminal, which also sends `\n`. But during normal operation it does not send `ok`.

**Comment by sfinexer** [comment]
@Harvie Probably you are right.
But if you do not send "OK" then after a while the programs stop.
https://github.com/vlachoudis/bCNC/issues/1108

**Comment by Harvie** [comment]
> But if you do not send "OK" then after a while the programs stop.

This might be a bug in bCNC, but i was not able to replicate it... Surely you will not fix it by arduino sending more `ok`s than stock GRBL. It will only hide the bug if there's any. Also it's possible that you have RF interference with serial line that prevents `ok` from being delivered...

**Comment by sfinexer** [comment]
The text "<Idle|MPos:0.000,0.000,0.000|FS:0,0|WCO:0.000,0.000,0.000>\r\n" is too long, having studied the GRBL code, the function printPgmString is used there, I copied it here.
It is necessary to test better, but the hang of the program at the moment is not observed.

**Comment by sfinexer** [comment]
I'm unsure of the correctness of changes, I ask users to test these changes.

**Comment by sfinexer** [comment]
I connected the Arduino with a short wire yesterday. And without "OK" she stopped ((((

**Comment by Harvie** [comment]
> without "OK" she stopped

Obviously. That's how GRBL streaming works.
https://github.com/gnea/grbl/wiki/Grbl-v1.1-Interface#streaming-a-g-code-program-to-grbl

**Comment by sfinexer** [comment]
@Harvie. Thank you very much.

So the patch is correct in terms of documentation.
But the question of stopping remains open.
The documentation for the Arduin, I think is not entirely correct, it says about the buffer size of 128 characters. However, UNO uses a buffer of 80 characters (grbl file config.h "#define LINE_BUFFER_SIZE 80 // Uncomment to override default in protocol.h").
But in my example, we use fake-grbl-arduino.ino and there in the code of my patch char buff [128];
However, the behavior of the program remains unpredictable.

**Comment by sfinexer** [comment]
@Harvie 
https://github.com/gnea/grbl/wiki/Grbl-v1.1-Interface#real-time-status-reports
It says that GRBL in theory may not respond to a state request (?) At all.
I have a question, does B-cnc expect an answer?
Judging from the description of the GRBL, the answer is optional, and B-cnc is not obliged to expect a response.
Indeed, in my case, there are no delays in performing the state response (?), Since fake-grbl-arduino.ino constantly "performs" the G-cod, and it does not have time to respond to requests for the state.

**Comment by Harvie** [comment]
> I have a question, does b-CNC expect an answer?

i think it does not expect answer. except when the `?` is issued manualy by user in terminal. In that case user will receive one status report printed to terminal. Other status reports are then silently procesed in background. Otherwise there would be hundreds of status reports printed in terminal all the time.

**Comment by sfinexer** [comment]
Accidentally deleted the patch.
I think it's worth the wait to read the SD card.
Probably, the problem is in the transmission of large data, since if the G-code contains less than 20k lines, the error is very rare.
I use G-code where about 150-200 thousand lines.

**Comment by Harvie** [comment]
I think we can write arduino code for "serial loopback" and test the arduino, if the usb-serial chip works properly at 115200 bauds.

**Comment by sfinexer** [comment]
In other words, the error is probably not in the response to the "?" or another command, namely the loss of data.

**Comment by Harvie** [comment]
I don't know, but we should check this. I few months agot i had nasty problems with chinese usb-serial chips running at 115200, so i think we need some tools to test it. Something like `Serial.write(Serial.read());` Then send lots of data to it, let it run for 10 minutes and check md5 sum of the data or something. Also do the same tests with motors running to test for EMI problems.

**Comment by sfinexer** [comment]
@Harvie 
Well, as I wrote earlier, I have a data buffer on the Arduino2560 (There are nominally more RX and TX). But as I wrote earlier, to my disregard, the buffer is writing to the SD card, but I still have nothing to read it.

**Comment by sfinexer** [comment]
Here is the test code for the Arduino 2560
[becap.ino.zip](https://github.com/vlachoudis/bCNC/files/2945813/becap.ino.zip)

**Comment by sfinexer** [comment]
The system I use:
```
B-cnc ---> Arduino2560 ---> ArduinoUNO
                \            /
                   SD card
```

**Comment by Harvie** [comment]
```C
void setup() {
  Serial.begin(115200);
}

void loop() {
  if (Serial.available()) {
    Serial.write(Serial.read());
  }
}
```

```bash
dd if=/dev/urandom of=random.bin bs=1M count=1
stty -F /dev/ttyUSB3 115200 cs8 ixoff
tail -f /dev/ttyUSB3 | pv > random2.bin

#Then in another terminal:
cat random.bin | pv > /dev/ttyUSB3
sleep 2 #wait until everything received
md5sum random.bin random2.bin

```

**Comment by sfinexer** [comment]
@Harvie I will try.
But the question arises, what to do is md5sum not match?

**Comment by sfinexer** [comment]
sfinexer@sfinexer:~/test$ tail -f /dev/ttyUSB1 | pv > random2.bin
00 B 0:00:23 [0,00 B/s] [<=>                                                                        ]

**Comment by Harvie** [comment]
Pay attention to this line: #Then in another terminal:

**Comment by sfinexer** [comment]
> Pay attention to this line: #Then in another terminal:

Thanks, I thought it after doing)

**Comment by sfinexer** [comment]
@Harvie random2.bin is not increasing.

**Comment by Harvie** [comment]
@sfinexer I've written better test for you:
https://github.com/vlachoudis/bCNC/tree/master/tests/arduino-loopback

**Pull request closed without merging**
