### PR TITLE
adaptive path for trochoidal cutting

### PR DESCRIPTION
**Pull request by MARIOBASZ**
Minor changes and notice that trochoid functionality adapting at the corners is not yet used in trochoid complement
With and without 
da67a3c4-1a50-44e6-ac2b-eceb4fe3a2b7

### CODE REVIEW

**Comment by Harvie** [comment]
Your fork got partialy out of sync from upstream, so it says this:

```
Traceback (most recent call last):
  File "bCNC.py", line 52, in <module>
    from CNC import WAIT, CNC, GCode
  File "/home/harvie/Temp/bCNC-mario/CNC.py", line 19, in <module>
    from bstl  import Binary_STL_Writer
ImportError: No module named bstl
```
To get it working you have to do this in your repository:

```
git pull https://github.com/vlachoudis/bCNC.git
git push origin master
```

That way it will reflect lastest changes from upstream repository
But still Troch_path is broken:

```
Traceback (most recent call last):
  File "/home/harvie/Temp/bCNC2/Utils.py", line 422, in __call__
    return self.func(*args)
  File "/home/harvie/Temp/bCNC2/ToolsPage.py", line 1550, in execute
    self.tools.getActive().execute(self.app)
  File "/home/harvie/Temp/bCNC2/plugins/TrochoidPath.py", line 69, in execute
    app.trochprofile_bcnc(self["CutDiam"], direction, self["Offset"], self["Overcut"], self["Adaptative"], cornerradius, name)
  File "bCNC.py", line 1820, in trochprofile_bcnc
    msg = self.gcode.trochprofile_cnc(blocks, ofs*sign, overcut, adaptative, adaptedRadius, name)
AttributeError: GCode instance has no attribute 'trochprofile_cnc'
```

**Comment by MARIOBASZ** [comment]
I do not know how to solve my problem in Git !! With my current resquest pull, if they upload it, is not it solved? Is there any other button "git push origin" from my folk? in git diff, it does not inform me error, yes this appears to me:
This branch is 4 commits ahead, 62 commits behind vlachoudis: master.
Can I delete all my files and start from scratch?

Anyway, see if the trochoid path add-up works. The warning to start adaptive trochoid is a not very elegant solution, a forward movement followed by another one backwards of 0.0001 (bpath -> def trochovercut -> DPolice). Surely you will find a more appropriate form of notice.
 In trocoid, when you see a segment of that measurement, it is notice to measure the next segment to: 1-start adaptive trochoid, 2- fast turn without trochoids (or trochoid 0)

**Comment by MARIOBASZ** [comment]
I am trying to generate a splice route in a smooth arc between trochoids, it still has errors.
Perhaps it also serves to generate an empame between curve and straight lines to soften the jerks
Still have errors
image
In the empame I run running the center of the first (cutting in blue) to the second center (radius in azu), and I have as parameters the radios (in this case both radios are the same)
image

**Comment by Harvie** [comment]
> With my current resquest pull, if they upload it, is not it solved? 

No. I downloaded upstream version and pulled your changes to it. does not work.

**Comment by MARIOBASZ** [comment]
Note that trochoid path generates the route (the adaptation start warning in a movement of 0.00001 or less due to rounding error when adding vectorially)

**Pull request closed without merging**
