### PR TITLE
Trochidal Icon

### PR DESCRIPTION
**Pull request by MARIOBASZ**
trochoidal

### CODE REVIEW

**Comment by Harvie** [comment]
try this in your repository:

git pull https://github.com/vlachoudis/bCNC.git

**Comment by MARIOBASZ** [comment]
thanks @Harvie, but I still do not know how to correct it

**Comment by Harvie** [comment]
You put icon directly into the project root. That's probably not what you intended:

https://github.com/MARIOBASZ/bCNC/blob/master/trochoidal.gif

**Comment by MARIOBASZ** [comment]
I can not delete the wrong file

**Comment by MARIOBASZ** [comment]
very interesting! I do not know if you have corrected it, but if I move the silhouettes considered as islands, the "islands" continue in the same place, and I do not see how to eliminate them (previously you could eliminate the marks in tabs) Can you do something similar to unmark islands?

**Comment by Harvie** [comment]
select and click "island" again. or just delete "island" from block name in editor.

**Comment by Harvie** [comment]
This is not good. You've re-commited some of my changes to your fork and pull request, this will lead to conflict if this gets merged. Please don't do this!

**Comment by MARIOBASZ** [comment]
ok, if I understand correctly: I upload to my branch the files as they are in the main branch so as not to generate conflicts! I assumed that after merging your changes, they would be compared or authorized with them by my aggregates, to avoid conflicts make a warning about what are after your work

**Pull request merged**
