### PR TITLE
Update sketch.py

### PR DESCRIPTION
**Pull request by sfinexer**
1) Possibility of accidentally first point for the line.
2) The algorithm of search of continuations of lines is improved
3) Choice of the fading level
ORIGINAL:
line1

OLD programm:
screenshot_20180926_130426
NEW programm:
screenshot_20180926_130445
OLD programm:
screenshot_20180926_131032
NEW programm:
screenshot_20180926_131104

### CODE REVIEW

**Comment by sfinexer** [comment]
The value of the maximum illumination is added
old:
screenshot_20180926_153604
NEW:
screenshot_20180926_153631
It prevents frequent repeated pass.

**Comment by sfinexer** [comment]
I have broken into blocks!
It is very important for function of optimization cnc of a code!

**Comment by Harvie** [comment]
OMG OMG! Can't wait to engrave my favorite apollonia saintclair drawings!

http://www.tumbex.com/tumblr/apolloniasaintclair/photo

**Comment by Harvie** [comment]
i would like to cut this, but as continuous lines, not as dots:

aposketch

**Comment by sfinexer** [comment]
Yes, the module of a line isn't ideal.
I have improved him within possible. For you, @Harvie, needs vector graphics.
This module yet not ideally does lines, but it works within put by the author.

Now I see need of the dots http://cnc.tiven.ru/image/2018-09-15_09-03-34.jpg module and the module of vector graphics.@Harvie

**Comment by sfinexer** [comment]
It is a mistake in the main file.
https://github.com/vlachoudis/bCNC/pull/979/commits/1b3ad97a31494b46b6b09dbfec4c799c6f0b8a2c

**Comment by Harvie** [comment]
If i trace bitmap in inkscape, every line is done twice. It's bad for handwriting and line art:

image

image

I think there's possibility of reverse that process using voronoi algorithm:

image

**Comment by MARIOBASZ** [comment]
interesting ... but excuse my ignorance. To mill or to use with pyrograph, especially in those of women similar to my mother-in-law? Can some example code send? maybe it will be easier for me to grasp the concept of what they are talking about

**Comment by sfinexer** [comment]
@MARIOBASZ Is there a video https://www.youtube.com/channel/UCIj-n4-Ovlp0RFvTbDWqL1g/videos?sort=dd&view_as=subscriber&view=0&shelf_id=0

**Comment by sfinexer** [comment]
@MARIOBASZ   https://www.youtube.com/watch?v=bv81fX2MVMo

**Comment by Harvie** [comment]
@sfinexer if you want your changes to be merged, please provide PR that does not contain Marios changes. I will need to review that separately.

**Comment by Harvie** [comment]
Ok. I had to redo the commits to fit latest master, but i've managed integrate all of your changes:
a5de961e672e412b8e9948d779bbaeed6fd587ed
f74065283c5bf1d67b8ca77ad582445686c0f934

and even some of @MARIOBASZ:
6a8fbd1a34bef0c89c26c0e42a846f4fb3c0c3c5
c477c32e8b922f3926c70c6c8fa51b6304c1a642

**Comment by Harvie** [comment]
Also. Before you commit any other changes. Please clone latest @vlachoudis master. Major refactoring took place and i will not be able to accept pull requests based on old branch anymore.

**Comment by Harvie** [comment]
Can you please take a look at following issue? #1254
You were the last one to make changes to that plugin...

Thanks

**Pull request closed without merging**
