### PR TITLE
Update Sender.py

### PR DESCRIPTION
**Pull request by maduka-ariyasiri**
INTEGRATED: -  
<issue>#1318</issue>  
<type> BUG FIX </type>  
<audience>Customer</audience>  
<description>connection problem due to serial decode </description>  
<options>None</options>  
<dependencies>None</dependencies>

### CODE REVIEW

**Review by dzervas — APPROVED** [review]

**Review by rschell — APPROVED** [review]
Wasn't having the problem, change doesn't appear to cause issues on my pi machine.

**Comment by maduka-ariyasiri** [comment]
PREPARED - d07763ef3e9f4f1c5447ac2ea2845e3ac5122e43

**Comment by maduka-ariyasiri** [comment]
Is there anyone here who can merge the pull request?  (have write permissions?)

**Comment by Harvie** [comment]
I would merge it, but it does have conflicts. Can you please rebase it?

**Comment by maduka-ariyasiri** [comment]
Hi Tomas,

 

Due to permission issues, I have closed #1720 pull request and created a new #1794 pull request. I'd appreciate it if you could review the edits and merge them.

 

https://github.com/vlachoudis/bCNC/pull/1794

 

Regards

Maduka

**Pull request closed without merging**
