### PR TITLE
Scale

### PR DESCRIPTION
**Pull request by MARIOBASZ**
Sorry for my clumsiness with Github. I'm still clumsy. I have uploaded icon and modified scale plugin to my branch. My branch keeps showing me conflicts with the main one, I do not know how to repair. The intention is to upload the icon and the improvements:
Corrections and improvements in scale.
Select several shapes. Scale from the center (only for individual selection and regular shapes except triangle).
Scale on 3D route.
For safety, Z scaling <= Zsafe
Returns straight line code (not G2 G3). Optimize with Arc fit.
Mario

### CODE REVIEW

**Comment by Harvie** [comment]
As you can see, the @vlachoudis  master is now very different from your's:

image

Also note, that i've already merged some of your changes to master, so you don't have to do that. Look at following commits to see what i've already merged:

6a8fbd1a34bef0c89c26c0e42a846f4fb3c0c3c5
c477c32e8b922f3926c70c6c8fa51b6304c1a642
77cb1f4f7bb089bb9a7b6107df81a0430fcf9119
ea3bcfc8e2211ff64b55600d56510d116df3c8c2

I've managed to adapt your changes to new master using meld. I don't really know how to do it purely by git. But this helped me to pick code from your copy to master. You just open two files and you click on the arrows to copy changes from one version to another:

http://meldmerge.org/
image

So you clone vlachoudis master, use meld to apply your changes and commit again. That's easiest way if you don't want to use any advanced git magic.

***

Also i don't want following feature:

```
			("zretract", "mm" ,   1.0, _("Z Distance before contact")),
			("feedbeforecontact", "int" ,   80, _("Z Feed before contact %")),
			("hardcrust", "mm" ,   1.0, _("Hard crust thickness")),
			("hardcrustfeed",  "int", 70, _("Hard crust Z Feed %"))
```

Maybe i will change my mind in the future, but i think this will be confusing for beginners (it's already too confusing, all these feeds and speeds might be scary for newcomers). If you have some multilayer material with different hardness, you should cut it in two or more operations (each cut can start at different height, see "surface Z").

image

Another reason why i don't like this feature: What if you have more than 2 layers of different hardness? Like this candy:

image

You can still make 20 different cuts with different "surface Z", but you can't do that using your "hard crust" feature.

So that's why i don't want to merge this. So i cannot not accept pull request which contains these changes.

**Comment by Harvie** [comment]
Also note, that i prefer clean 16x16 icons manualy made pixel by pixel. I do it using kolourpaint at high zoom. In this style:

image

I've already made icon for scaling, so there's no need for that.

**Comment by MARIOBASZ** [comment]
Thanks @Harvie, I value your dedication!
I will review your comments carefully. First of all I will try to update my branch to avoid conflicts (I mistakenly assumed that Git only raised the requested: scale)

**Comment by Harvie** [comment]
OK. Thanks. I am looking forward to test adaptive trochoids. I merged it to master, but it still gives me an error :-( I've tried, but failed to fix the error.

**Comment by Harvie** [comment]
Any news on this?

**Comment by MARIOBASZ** [comment]
hello @harvie, I've been busy, I must try to resolve conflicts with the master branch, I'm still clumsy with github.
If you want you can try corrected scale, it works better.
I have seen that adaptive trocoid path does not run, the modifications in cnc and bcnc.py files have not been copied, (in my repository they are, I am not in my machine but if I remember correctly they appear as trochoid profile) ... no I remember if there is another modified file, plus a little trick so that trochoid finds out that he is in the position of "adaptive initiation", trick to improve. By the way, I do not know if you have used a trochoidal cut ... it is surprising: I have drilled 13mm aluminum in a single pass, (my machine has a 500W spindle, in a traditional cut with passes greater than 0.10mm in depth) , with cutter 6.00mm, diameter 7.50 slot -> trochoid diameter 1.50, ae = 0.03mm F500 rpm 12000, upload video

**Comment by Harvie** [comment]
> I must try to resolve conflicts with the master branch

I think at this point it would be easiest to pull fresh clone of master and try to reapply your changes onto that.

**Comment by MARIOBASZ** [comment]
I can delete all the files in my branch, or delete repository and upload again from the main branch, if it does not generate conflict

**Comment by Harvie** [comment]
> I can delete all the files in my branch

You must understand that git is not just about files, it's also about commits (the history). This is how you are supposed to do

1.) fork vlachoudis to mario
2.) clone mario to your laptop (use git clone to your laptop, rather than just downloading/uploading files via github web!)
3.) in mario directory do "git pull" of vlachoudis to integrate latest vlachoudis changes to your tree
4.) if there are conflicts between mario and vlachoudis, git will tell you and you have to fix and commit
5.) do some changes and commit them
6.) push from laptop to mario (your github account)
7.) open pull request (mario->vlachoudis) if you don't have one open yet
8.) repeat from 3.) as needed

This will keep your fork up to date with vlachoudis. When you initiate "pull request" it means that you want me to do "git pull" of your fork to upstream. But you also have to do "git pull" of upstream to your fork. That way you get latest changes to your fork and i can get your changes to upstream. "git pull" is for taking changes that friend makes and applying them to your copy. We both have to do it in order to stay in sync.

The less often you pull from me, the more our forks get different. And more differences means it's more painfull to merge two versions together for both of us. Sometimes it's just easier to clone upstream and redo (commit) the changes again from scratch. Also you should create the pull requests often, so i keep track of your changes in upstream (but it has to be working code that will not crash rest of bCNC).

Read some git workflow basics or watch some videos about this. Especialy you should learn how to use these git commands:
status, commit, clone, push, pull, diff, log
You rarely need more git commands than this. as bonus this is nice thing to put into your CV :-)

**Comment by Harvie** [comment]
So basicaly you deleted all of the files. If i merge now, it will delete all our files.
Stop thinking about git as if it was file storage. Think about it as history log of changes (commits).

If you want to overwrite your repository with empty fork, you have to do new "git clone" of vlachoudis to new directory in your pc, then go to that directory and do "git push -f" to your github repo URL.

**Comment by MARIOBASZ** [comment]
Sorry, I tried to upgrade from Master to Mario, not the other way around (when I did pull, I was informed "nothing to update" even though before I reported "I'm behind vlachouis".
I think I solved the problem. (Delete fork from Github, clone new Fork) And thank you for your interest.
I hope to continue helping (currently not yet completed: improved scale (also be able to generate conical gear, backlash, correct orthogonal machine).
About adaptive trocoide in corners, if you help me with a small modification to adaptive path (how to generate a warning "here starts adaptive" and "here ends adaptive" similar to islands and cut (or tell me where to find faster) I avoid my artificial way (currently I move 0.00001 and back again 0.00001 to indicate start and end, ... although I forgot where I had inserted this movement, my memory is weak point, and upload the corresponding modifications to .py files bcnc and cnc

**Comment by MARIOBASZ** [comment]
Do you know how to live this better?

**Comment by MARIOBASZ** [comment]
If you can, delete this commit

**Comment by Harvie** [comment]
Commit? I can only close this pull request if you don't want it anymore. But you can do it yourself.

**Pull request closed without merging**
