### PR TITLE
overcuts and additional cuts

### PR DESCRIPTION
**Pull request by DodoLaSaumure**
Add overcuts and additional cuts inside corners

### CODE REVIEW

**Comment by DodoLaSaumure** [comment]
And you can now manage overcuts inside / outside pockets :)

**Comment by DodoLaSaumure** [comment]
Maybe we can reduce rapid moves between overcuts, but as I am not sure to succeed, I prefer pushing this previously to attempt

**Comment by DodoLaSaumure** [comment]
That was easy in fact. ;)

**Comment by DodoLaSaumure** [comment]
I think it's ok now.
Pierre

**Comment by Harvie** [comment]
Thank you... So far i was not able to find any issue.
Only thing that comes to my mind is ignoring the islands:

1.) Add checkbox "ignore islands", so users can easily get back the original behaviour
2.) By default ignore all islands marked as "tab"... I see very little point in affecting profiles and pockets by tabs. These will be handled in cutting operation anyway... So perhaps tabs should be ignored always.

**Comment by Harvie** [comment]
Also it might be useful to add option "only regard selected islands", so user can select which islands to use.

When this is done, i will try to integrate this to the bCNC UI.

**Comment by DodoLaSaumure** [comment]
Hi Thomas, 
This has been done in #1545

**Pull request merged**
