### PR TITLE
Optimize function

### PR DESCRIPTION
**Pull request by sfinexer**
It is corrected.
In case the speed of CNC.feedmax_x CNC.feedmax_y different optimize correctly works!

### CODE REVIEW

**Comment by Harvie** [comment]
Can you please explain how this works? Why it's needed to divide distance by feedrate when rearanging blocks?

**Comment by Harvie** [comment]
Also this commit is already in #979 
I don't see no need to merge it separately

**Comment by sfinexer** [comment]
@Harvie 
Instead of the distance between the points apply arrival time.
This is necessary if different speeds of movement of the machine along individual axes.

**Comment by Harvie** [comment]
And what will happen when somebody will use bCNC just as g-code editor without ever connecting it to the machine?

**Comment by sfinexer** [comment]
@Harvie It is necessary to take parameters not of the controller and the bCNC config.

**Comment by sfinexer** [comment]
Feed max x
Feed max y
Feed max z

**Pull request closed without merging**
